#!/bin/bash

set -e

OUTDIR=cdp-$VERSION

# Creem els directoris
mkdir -p $OUTDIR $OUTDIR/Rlibraries $OUTDIR/Rscripts $OUTDIR/Help

# Descomprimim els programes externs
# tar xzvf external-programs/jdk-17.0.7_${VERSION}_bin.tar.gz -C $OUTDIR
tar xzvf external-programs/bellsoft-jdk17.0.15+10-${VERSION}.tar.gz -C $OUTDIR
mv $OUTDIR/jdk-17.0.15.jdk $OUTDIR/jdk-17

unzip -n external-programs/apache-maven-3.9.2.zip -d $OUTDIR
cp -rf external-programs/create-dmg $OUTDIR

# Copiem el codi font
cp -rf src $OUTDIR

# Copiem els Rscripts i Help amb rsync (més robust)
rsync -av Rscripts/ $OUTDIR/Rscripts/
rsync -av Help/ $OUTDIR/Help/

# Copiem els scripts de construcció
cp -f build-codapack-macos $OUTDIR/build-codapack
cp -f run-codapack-macos $OUTDIR/run-codapack
cp -f build_app.sh $OUTDIR/build-app

# Generem l’script build-dmg
cat << EOF > $OUTDIR/build-dmg
#!/bin/bash
set -e
./create-dmg/create-dmg \\
    --volname "CoDaPack" \\
    --volicon "src/main/resources/icons.icns" \\
    --background "src/main/resources/background.png" \\
    --window-pos 200 120 \\
    --window-size 800 500 \\
    --icon-size 100 \\
    --icon "CoDaPack.app" 200 200 \\
    --app-drop-link 600 200 \\
    "CoDaPack-${VERSION}.dmg" \\
    "CoDaPack.app"
EOF

chmod +x $OUTDIR/build-dmg

# Altres fitxers de configuració
cp -f install_packages.R $OUTDIR
cp -f codapack_structure.yaml $OUTDIR
cp -f license.txt $OUTDIR
cp -f pom.xml $OUTDIR

# Permisos
chmod -R a+x $OUTDIR/apache-maven-3.9.2/bin
chmod a+x $OUTDIR/build-codapack
chmod a+x $OUTDIR/run-codapack
chmod a+x $OUTDIR/build-app

# Empaquetem el resultat final
(cd $OUTDIR && zip -X -r ../codapack-$VERSION.zip .)