#!/usr/bin/bash

OUTDIR=cdp-windows

mkdir $OUTDIR -p
mkdir $OUTDIR/Rlibraries -p
mkdir $OUTDIR/Rscripts -p

unzip -n windows-programs/jdk-17.0.7_windows-x64_bin.zip -d $OUTDIR
unzip -n windows-programs/R-4.3.1.zip -d $OUTDIR
unzip -n windows-programs/apache-maven-3.9.2.zip -d $OUTDIR

cp -rf src $OUTDIR

cp -f Rscripts/*.R $OUTDIR/RScripts/
cp -f build-codapack.bat $OUTDIR
cp -f run-codapack.bat $OUTDIR
cp -f install_packages.R $OUTDIR
cp -f codapack_structure.json $OUTDIR
cp -f pom.xml $OUTDIR

# (cd cdp-windows && zip -r ../codapack-windows-x64.zip -r .)
