/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataList.java
 *
 * Created on 22/09/2010, 11:54:48
 */

package coda.gui;

import coda.DataFrame;
import javax.swing.DefaultListModel;

/**
 *
 * @author mcomas
 */
public class DataList extends javax.swing.JPanel {
    public static final long serialVersionUID = 1L;
    //private String rootName = "CoDaPack";

    public DataList() {
        initComponents();
    }
    public void setData(DataFrame df){
        //frames.add(df);
        //frame = df;
        DefaultListModel model = new DefaultListModel();
        for(String name : df.getNames())
            model.addElement(name);
        /*
        Iterator it = df.getNamesIterator();
        while(it.hasNext()){
            model.addElement((String)it.next());
        }*/
        dataList.setModel(model);
    }
    public int[] getSelectedData(){
        return dataList.getSelectedIndices();
    }
    public void clearData(){
        dataList.setModel(new DefaultListModel());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataList = new javax.swing.JList();

        setPreferredSize(new java.awt.Dimension(175, 500));
        setLayout(new java.awt.BorderLayout());
        
        jScrollPane1.setPreferredSize(new java.awt.Dimension(175, 500));        
        jScrollPane1.setViewportView(dataList);
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList dataList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
